import React from 'react'

export default function background() {
   const keywords = [
      'logic',
      'software',
      'engineer',
      'personal',
      'jakarta',
      'dev',
      'social',
      'refresh',
      'glitch',
      'performance',
      'bug',
      'animation',
      'freelance',
      'next-js',
      'webpack',
      'class',
      '.id',
      'digital',
      'develop',
      '.com',
      'seo',
      '</>',
      'network',
      'hello world!',
      'console.log',
      'react-dom',
      'coding',
      'node',
      'developer',
      'code',
      'html',
      'build',
      'version',
      'firebase',
      'scss',
      'blog',
      'state',
      'hooks',
      'express',
      'redux',
      'life-cycle',
      'front-end',
      'debug',
      '404',
      'critical',
      'thinking',
      'css',
      'web',
      'terminal',
      'work',
      'linkedin',
      'sass',
      'layout',
      'depedencies',
      'useEffect',
      'problem solver',
      'npm',
      'useState',
      'yarn',
      'repository',
      'api',
      'database',
      'dream',
      'job',
      'node_modules',
      'index',
      'app',
      'website',
      'design',
      'build',
      'web dev',
      'keyframes',
      'tech stack',
      'figma',
      'bem',
      'reset',
      'normalize',
      'responsive',
      'partner',
      'concept',
      'error',
      'not found',
      'learn',
      'visual',
      'indonesia',
      'git',
      'vs code',
      'user-interface',
      'project',
      'element',
      'technical',
      'programmer',
      'cv',
      'tech',
      'context',
      'javascript',
      'reactjs',
   ]
   return (
      <div className='background'>
         {keywords.map((item) => {
            return <h5 className='text-keyword'>{item}</h5>
         })}
      </div>
   )
}
